# Generated by Django 3.0.7 on 2020-06-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_mode',
            field=models.CharField(choices=[('PP', 'Paypal'), ('CB', 'Virement bancaire'), ('WU', 'Western Union'), ('MG', 'MoneyGram'), ('RA', 'Ria'), ('CH', 'Cash')], default='CH', max_length=2),
        ),
    ]
