# Generated by Django 3.0.7 on 2020-06-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_auto_20200610_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Modes de paiement',
            },
        ),
        migrations.RemoveField(
            model_name='expense',
            name='payment_mode',
        ),
        migrations.AddField(
            model_name='expense',
            name='payment',
            field=models.CharField(default='Cash', max_length=200),
        ),
    ]
