# Generated by Django 3.0.7 on 2020-12-01 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_auto_20200610_1217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'verbose_name_plural': 'Dépenses'},
        ),
    ]
