# Generated by Django 3.0.7 on 2020-12-01 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userincome', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userincome',
            options={'verbose_name_plural': 'Revenus'},
        ),
    ]
